var paragraphs = 
{
    General:[
        ["A Snake Charmer", "A snake charmer is a person who moves the streets with different types of the banks of the river yamuna. It is snakes in his basket. He goes from one place to another to show various types of snakes and their tricks. He carries a pipe with which he plays music and snakes dance to his tune. He usually wears a colourful dress. The job of a snake charmer is quite dangerous. Some snakes are quite poisonous and can even bite him. It is not an easy task to catch and train them for the shows."],
    
        ["The bird I like most", "The bird I like most is the parrot. The parrot is a very beautiful bird. Its feathers are green. It has a red beak. Its beak is curved. Round the neck of a parrot there are black rings. Overall it is a lovely looking bird. It eats grains, fruits, leaves seeds, pears, nuts, mangoes and boiled rice etc. The Parrot is a talking bird. It can imitate the human voice. It is found in almost all the warm countries. It generally lives in the hollows of trees. Some people keep it in a small cage which is not good. Some people train parrots to do wonderful things."],
        
        ["Street Begger", "A street beggar can be seen everywhere; at the bus stop, railway stations, religious places, markets etc. Some beggars are crippled, lame and some are blind. They are unable to earn their livelihood. Whereas some are healthy and they do not deserve our sympathy. We should see that they take up some profession. They should not be allowed to beg. On my way to school I see a beggar daily. He wears old rags. He is partially blind. I feel pity seeing him but I can't help it I can only pray to God to help him to earn his livelihood."],
        
        ["What is Coal", "Coal is a very useful hard and black material collected from mines. The woods buried under the earth for a long time turn into coal by some chemical change. Earthquakes cause vast forest areas to dip underground and help to bring about such changes due to tremendous heat and pressure. In our country coal mines are found at Asansol, Raniganj, Dhanbad, Jharia, Giridih, Chaibasa, etc. India exports coal to Japan, Nepal, and Bangladesh. Coal is used as fuel for domestic purposes and also in factories and industries. Most of the trains and steamers move by consuming coal in steam engines."],

        ["Why do Atoms Explode when they are Split?", "Atoms of radioactive elements can be spilled. According to Albert Einstein, mass and energy are interchangeable under certain conditions. When the atom splits, the process is called nuclear fission. In this case, a tiny amount of mass is converted into energy. The energy thus released cannot do much damage. However, a number of subatomic particles called neutrons are also released during this process. Each neutron will hit a radioactive element releasing more neutrons in the process. This results in a chain reaction and a tremendous amount of energy is created. This energy is converted into heat which expands uncontrollably causing an explosion."],

        ["Power of Positive Thinking", "Positive thinking is an attitude or a mindset characterized by optimism and happiness. A positive person hopes for the best and anticipates success in his life. Although many may scoff at the idea of always being positive, it has a plethora of benefits not only for the mind but also for the body. Positivity imparts happiness to the soul and makes one lighter. This causes us to exude goodwill and joy. People are drawn towards such individuals. Being negative in one‟swords and actions causes the exact opposite reaction. It is a known fact that people try to avoid people who relay negativity."],
    ],
    React:
    [
        ['Create React Application', 'Facebook has created a Create React Application with everything you need to build a React app. It is a development server that uses Webpack to compile React, JSX, and ES6, auto-prefix CSS files. The Create React App uses ESLint to test and warn about mistakes in the code. To create a Create React App run the following command on your terminal "create-react-app myProject". Make sure you have installed create-react-app command globally in your system, otherwise you need to install it first.'],

        ["What is React Component?", 'Components are rightly defined as the essential building blocks of any application created with React, and a single app most often consists of many components. A component is in essence, a piece of the user interface - splitting the user interface into reusable and independent parts, each of which can be processed separately. We can reuse a component used in one area of the application in another area. This speeds up development and helps avoid cluttering of code. A component can contain within itself, several more components.  This helps in creating more complex design and interaction elements.'],
        
        ["What is Redux", `Redux is a predictable state container for JavaScript applications. It helps you write apps that behave consistently, run in different environments (client, server, and native), and are easy to test. Redux manages an application's state with a single global object called Store. Redux is a state management tool. Redux can be used with any JavaScript framework or library. Redux stores the state of the application, and the components can access the state from a state store. The state of your whole application is stored in an object tree within a single store. The only way to change the state is to initiate an action, an object describing what happened.`],

        ["React Component Life-Cycle", "In ReactJS, Life cycle of a component represents the different stages of the component during its existence. The lifecycle of the component is divided into four phases. They are: Initial Phase (It is the birth phase of the lifecycle of a ReactJS component. Here, the component starts its journey on a way to the DOM), Mounting Phase (Mounting represents the rendering of the React component in the given DOM node), Updating Phase (Updating represents the re-rendering of the React component in the given DOM node during state changes/updates), Unmounting Phase (Unmounting represents the removal of the React component). Each phase contains some lifecycle methods that are specific to the particular phase."],

        ["React VDOM", "React uses Virtual DOM exists which is like a lightweight copy of the actual DOM(a virtual representation of the DOM). So for every object that exists in the original DOM, there is an object for that in React Virtual DOM. It is exactly the same, but it does not have the power to directly change the layout of the document. Manipulating DOM is slow, but manipulating Virtual DOM is fast as nothing gets drawn on the screen. So each time there is a change in the state of our application, the virtual DOM gets updated first instead of the real DOM."],
    ],
    JavaScript:
    [
        ["What is JavaScript?", "JavaScript is a dynamic programming language that's used for web development, in web applications, for game development, and lots more. It allows you to implement dynamic features on web pages that cannot be done with only HTML and CSS. Many browsers use JavaScript as a scripting language for doing dynamic things on the web. Any time you see a click-to-show dropdown menu, extra content added to a page and dynamically changing element colors on a page, to name a few features, you're seeing the effects of JavaScript. It was first known as LiveScript, but Netscape changed its name to JavaScript, possibly because of the excitement being generated by Java."],
        
        ["What is call stack?", 'A call stack is a mechanism for an interpreter (like the JavaScript interpreter in a web browser) to keep track of its place in a script that calls multiple functions, what function is currently being run and what functions are called from within that function, etc. When a script calls a function, the interpreter adds it to the call stack and then starts carrying out the function. Any functions that are called by that function are added to the call stack further up and run where their calls are reached. When the current function is finished, the interpreter takes it off the stack and resumes execution where it left off in the last code listing. If the stack takes up more space than it was assigned, a "stack overflow" error is thrown.'],

        ["What is Promise in JavaScript?", "Promises are used to handle asynchronous operations in JavaScript. They can handle multiple asynchronous operations easily and provide better error handling than callbacks and events. In other words, we may say that promises are the ideal choice for handling multiple callbacks at the same time, thus avoiding the undesired callback hell situation. A Promise is a special JavaScript object. It produces a value after an asynchronous (aka, async) operation completes successfully, or an error if it does not complete successfully due to time out, network error, and so on. Successful call completions are indicated by the resolve function call, and errors are indicated by the reject function call."],

        ["What is currying in JavaScript?", "Currying simply means evaluating functions with multiple arguments and decomposing them into a sequence of functions with a single argument. In other terms, currying is when a function instead of taking all arguments at one time, takes the first one and returns a new function, which takes the second one and returns a new function, which takes the third one, etc. until all arguments are completed. There are several reasons why currying is ideal. It helps you to avoid passing the same variable again and again. It divides your function into multiple smaller functions that can handle one responsibility, this makes your function pure and less prone to errors and side effects."],
    ]
    // testing:["What is HTML", "html is markup language."]
}

var getContent = () =>
{
    // return paragraphs["React"][3]
    var keys = Object.keys(paragraphs)
    var key = keys[Math.floor(Math.random() * keys.length)];
    var data  = paragraphs[key][Math.floor(Math.random() * paragraphs[key].length)]
    return data;
    // return paragraphs.testing
}
export default getContent